### ISSUE TITLE
Rename gocept.jsform

### ISSUE THREAD

**Issue by florianpilz** [gocept/ajja#46]
It's not a very catchy name and strongly coupled with our company.

Thoughts so far:
- Bread (from BREAD, an alternative acronym of CRUD)
- Slime (since CRUD means dirt and dirt leads to ...)
- It should be clear how to write the name when hearing it.
- It should somehow contain or undermine the basic idea of the library. So best start with 1 sentence describing the library and find a name starting at that sentence.
- The name should be unique, so ranking high in Google is easy and we do not compete with usual nouns.

**Comment by sweh** [comment]
Resolved
